### ISSUE TITLE
New features for loggable-decorator

### ISSUE THREAD

**Issue by garciparedes** [ateliedocodigo/python-loggable-wrapper#1]
Hi @luiscoms ! First of all, I want to congrats you for `loggable-decorator` project. I feel that it's really interesting, allowing us to manage `logging` import easily.

About few days ago, I started to think about the implementation of something similar to this package, managing logging over a system keeping it more transparent, so we could focus more on the business code. 

Because of that, I though in a decorator who submits logging messages automatically when some function or class is being called. After I see your package, I believe that an interesting way to implement that functionality could be to extend this project.

I don't know if you're interested to continue with this (maybe I could implement it and do a Pull request), or if you think an independent fork it's a better alternative, I will choose it.

**Comment by luiscoms** [comment]
Hi @garciparedes, feel free to open a Pull Request with other features! That is cool

**Comment by garciparedes** [comment]
Ok! I'll try to get some time to expend on it these days!
