### ISSUE TITLE
Make backward compatible

### ISSUE THREAD

**Issue by luiscoms** [ateliedocodigo/python-loggable-wrapper#14]
Before #9 the import

```python
from loggable import loggable, loggable_class, loggable_method
```

It should be fixed

**Comment by pratik97** [comment]
I can work on this

**Comment by pratik97** [comment]
@luiscoms apart from ignoring flake8 is there any nice way to do this?

**Comment by luiscoms** [comment]
A way to solve it is move the code from `loggable/loggable.py` to `loggable.py`

**Comment by pratik97** [comment]
Removing `loggable` from a package worth the backward compatibility? IMHO, adding flake8 exception for `__init__.py` is a better trade-off. What do you think?

**Comment by luiscoms** [comment]
Agreed, should you add a flake8 ignore
