### ISSUE TITLE
Add tox tests

### ISSUE THREAD

**Issue by luiscoms** [ateliedocodigo/python-loggable-wrapper#5]

**Comment by jnduli** [comment]
I want to work on this. I've seen there is an assert that checks logMessages (https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertLogs) but this is only supported from python 3.4. Will this be an ok way of adding tests?

**Comment by luiscoms** [comment]
@jnduli This is an example of [tox file](https://github.com/ateliedocodigo/py-healthcheck/blob/develop/tox.ini)

**Comment by jnduli** [comment]
Cool. I'll try to work on this and submit a PR.

**Comment by luiscoms** [comment]
Should you add flake8 command on tox file too?

**Comment by jnduli** [comment]
Yeah I should. I'll add it too.
